CREATE TABLE signal (
    signal_id       INTEGER PRIMARY KEY ASC,
    day_num         FLOAT NOT NULL,
    vehicle_id      INT NOT NULL,
    trip_id         INT NOT NULL,
    time_stamp      INT NOT NULL,
    latitude        FLOAT NOT NULL,
    longitude       FLOAT NOT NULL,
    speed           FLOAT,
    maf             FLOAT,
    rpm             FLOAT,
    abs_load        FLOAT,
    oat             FLOAT,
    fuel_rate       FLOAT,
    ac_power_kw     FLOAT,
    ac_power_w      FLOAT,
    heater_power_w  FLOAT,
    hv_bat_current  FLOAT,
    hv_bat_soc      FLOAT,
    hv_bat_volt     FLOAT,
    st_ftb_1        FLOAT,
    st_ftb_2        FLOAT,
    lt_ftb_1        FLOAT,
    lt_ftb_2        FLOAT
);